name: Code Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Dependencies
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
      
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Generate code coverage
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput='../TestResults/'

    - name: Generate report
      run: reportgenerator "-reports:TestResults/coverage.cobertura.xml" "-targetdir:coveragereport" -reporttypes:Html

    - uses: actions/upload-artifact@v2
      with:
        name: codecov-report
        path: coveragereport/
